use_frameworks!

platform :ios, '8.0'

target 'PYBaseNavigationController_Example' do
  pod 'PYBaseNavigationController', :path => '../'

  target 'PYBaseNavigationController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
